package chanaka.gui;

import chanaka.dao.StudentDAO;
import chanaka.data.Student;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class AddOrEditStudent extends javax.swing.JDialog {

    StudentDAO studentDAO;
    private Student selectedStudent;
    private String previousAdmissionNumber;
    boolean This_is_AddMode_but_not_EditMode;

    public AddOrEditStudent(java.awt.Frame parent, boolean modal, StudentDAO studentDao) {
        super(parent, modal);
        initComponents();
        studentDAO = studentDao;
        This_is_AddMode_but_not_EditMode = true;
    }

    public AddOrEditStudent(java.awt.Frame parent, boolean modal, StudentDAO studentDao, Student student) {
        super(parent, modal);
        initComponents();
        studentDAO = studentDao;
        this.previousAdmissionNumber = student.getAdmissionNumber();
        this.selectedStudent = student;
        This_is_AddMode_but_not_EditMode = false;
        populateData(student);
        btnAdd.setText("Save");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNameWithInitial = new javax.swing.JTextField();
        txtFullnameEnglish = new javax.swing.JTextField();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtFullNameSinhala = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtClassOfAdmission = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtAdmissionNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dchBirthDate = new com.toedter.calendar.JDateChooser();
        dchDateOfAdmission = new com.toedter.calendar.JDateChooser();
        cboReligion = new javax.swing.JComboBox();
        cboHouse = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add or edit student details");
        setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height));
        setResizable(false);

        jScrollPane1.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height));

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel1.setText("Add Student");

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel2.setText("Name with initials:");

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel3.setText("Full name (English):");

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel4.setText("Gender");

        txtNameWithInitial.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        txtFullnameEnglish.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        txtFullnameEnglish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFullnameEnglishKeyReleased(evt);
            }
        });

        buttonGroupGender.add(rdoMale);
        rdoMale.setText("Male");

        buttonGroupGender.add(rdoFemale);
        rdoFemale.setText("Female");

        jLabel5.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel5.setText("Date of birth:");

        jLabel11.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel11.setText("Address:");

        txtAddress.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel12.setText("Telephone no:");

        txtTelephone.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel13.setText("Date of admission:");

        btnAdd.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel9.setText("Full name (Sinhala):");

        txtFullNameSinhala.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel15.setText("House:");

        jLabel20.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel20.setText("Religion:");

        txtClassOfAdmission.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel23.setText("Class of admission:");

        txtAdmissionNo.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        txtAdmissionNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdmissionNoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel10.setText("Admission number:");

        cboReligion.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        cboReligion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buddism", "Catholic", "Hindu", "Islam" }));

        cboHouse.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        cboHouse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "විජය", "ගැමුණු", "පරාක්‍රම", "තිස්ස" }));

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel6.setText("නම:");

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel7.setText("පියාගේ විස්තර");

        jLabel8.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel8.setText("මවගේ විස්තර");

        jLabel14.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel14.setText("රැකියාව:");

        jLabel16.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel16.setText("රැකියාව කරන ස්ථානය:");

        jLabel17.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel17.setText("රැකියා ස්ථානයේ ලිපිනය:");

        jLabel18.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jLabel18.setText("දුරකථන අංක:");

        jTextField1.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jTextField6.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jTextField7.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jTextField8.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jTextField9.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jTextField12.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField13.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel19.setText("නිවස:");

        jLabel21.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel21.setText("ජංගම:");

        jLabel22.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel22.setText("රැකියා ස්ථානය:");

        jTextField10.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jTextField16.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        jTextField17.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel24.setText("නිවස:");

        jLabel25.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel25.setText("ජංගම:");

        jLabel26.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        jLabel26.setText("රැකියා ස්ථානය:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel23)
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFullnameEnglish, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
                                        .addComponent(txtFullNameSinhala)
                                        .addComponent(txtAdmissionNo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNameWithInitial, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(94, 94, 94)
                                            .addComponent(rdoFemale))
                                        .addComponent(rdoMale)
                                        .addComponent(dchBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dchDateOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtClassOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel22)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel19)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(55, 55, 55)
                                                    .addComponent(jLabel21)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel26)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(50, 50, 50)
                                                    .addComponent(jLabel24)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel25)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(cboHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtAdmissionNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFullnameEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameWithInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFullNameSinhala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rdoMale)
                            .addComponent(rdoFemale))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dchBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(dchDateOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cboHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(cboReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtClassOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(35, 35, 35))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(35, 35, 35))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel22)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel25))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1249, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdmissionNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdmissionNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdmissionNoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if ("".equals(txtAdmissionNo.getText())) {
            txtAdmissionNo.setText(JOptionPane.showInputDialog("Enter the admission number"));
        }
        if (!"".equals(txtAdmissionNo.getText())) {

            if ("".equals(txtFullnameEnglish.getText())) {
                txtFullnameEnglish.setText(JOptionPane.showInputDialog("Enter full name in English"));
            }
            if (!"".equals(txtFullnameEnglish.getText())) {
                if (rdoMale.isSelected() || rdoFemale.isSelected()) {
                    try {
                        saveOrUpdateStudent();
                        JOptionPane.showMessageDialog(rootPane, "Saved succesfully");
                        this.dispose();
                    } catch (SQLException ex) {
                        Logger.getLogger(AddOrEditStudent.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(rdoFemale, "Select the gender");
                }

            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtFullnameEnglishKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullnameEnglishKeyReleased
        fillNameWithInitial();
    }//GEN-LAST:event_txtFullnameEnglishKeyReleased

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    public void saveOrUpdateStudent() throws SQLException {

        String admissionNumber = txtAdmissionNo.getText();
        String fullNameEnglish = txtFullnameEnglish.getText();
        String fullNameSinhala = txtFullNameSinhala.getText();
        String nameWithInitials = txtNameWithInitial.getText();
        Date birthDate;

        try {
            birthDate = new java.sql.Date(dchBirthDate.getDate().getTime());
        } catch (NullPointerException e) {
            birthDate = null;
        }

        String house = cboHouse.getSelectedItem().toString();
        String religion = cboReligion.getSelectedItem().toString();
        String address = txtAddress.getText();
        String telephoneNumber = txtTelephone.getText();
        Date dateOfAdmission;
        try {
            dateOfAdmission = new java.sql.Date(dchDateOfAdmission.getDate().getTime());
        } catch (NullPointerException e) {
            dateOfAdmission = null;
        }
        String classOfAdmission = txtClassOfAdmission.getText();

        String gender = null;
        if (rdoMale.isSelected()) {
            gender = "Male";
        } else if (rdoFemale.isSelected()) {
            gender = "Female";
        }

        Student tempStudent = null;

        if (This_is_AddMode_but_not_EditMode) {
            tempStudent = new Student(admissionNumber, fullNameEnglish, fullNameSinhala, birthDate, house, religion, address, telephoneNumber, dateOfAdmission, classOfAdmission, gender, nameWithInitials);
            studentDAO.addStudent(tempStudent);

        } else if (!This_is_AddMode_but_not_EditMode) {

            tempStudent = selectedStudent;

            tempStudent.setAdmissionNumber(admissionNumber);
            tempStudent.setFullNameEnglish(fullNameEnglish);
            tempStudent.setFullNameSinhala(fullNameSinhala);
            tempStudent.setBirthDate(birthDate);
            tempStudent.setHouse(house);
            tempStudent.setReligion(religion);
            tempStudent.setAddress(address);
            tempStudent.setTelephoneNumber(telephoneNumber);
            tempStudent.setDateOfAdmission(dateOfAdmission);
            tempStudent.setClassOfAdmission(classOfAdmission);
            tempStudent.setGender(gender);
            tempStudent.setNameWithInitials(nameWithInitials);
            studentDAO.updateStudent(tempStudent, previousAdmissionNumber);
        }
    }

    public void populateData(Student student) {

        txtAdmissionNo.setText(student.getAdmissionNumber());
        txtFullnameEnglish.setText(student.getFullNameEnglish());
        txtFullNameSinhala.setText(student.getFullNameSinhala());
        dchBirthDate.setDate(student.getBirthDate());
        cboHouse.setSelectedItem(student.getHouse());
        cboReligion.setSelectedItem(student.getReligion());
        txtAddress.setText(student.getAddress());
        txtTelephone.setText(student.getTelephoneNumber());
        dchDateOfAdmission.setDate(student.getDateOfAdmission());
        txtClassOfAdmission.setText(student.getClassOfAdmission());
        txtNameWithInitial.setText(student.getNameWithInitials());
        String gender = student.getGender();
        switch (gender) {
            case "Male":
                rdoMale.setSelected(true);
                break;
            case "Female":
                rdoFemale.setSelected(true);
                break;
        }

    }

    void fillNameWithInitial() {
        String tempName = txtFullnameEnglish.getText();
        String[] nameList = tempName.split(" ");
        String nameWithInitial = "";
        for (int ui = 0; ui < nameList.length - 1; ui++) {
            nameWithInitial += nameList[ui].substring(0, 1) + ". ";
        }
        nameWithInitial += nameList[nameList.length - 1];

        txtNameWithInitial.setText(nameWithInitial);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JComboBox cboHouse;
    private javax.swing.JComboBox cboReligion;
    private com.toedter.calendar.JDateChooser dchBirthDate;
    private com.toedter.calendar.JDateChooser dchDateOfAdmission;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAdmissionNo;
    private javax.swing.JTextField txtClassOfAdmission;
    private javax.swing.JTextField txtFullNameSinhala;
    private javax.swing.JTextField txtFullnameEnglish;
    private javax.swing.JTextField txtNameWithInitial;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
