/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chamin.gui;

import chamin.dao.ClubDAO;
import chamin.dao.DbConnector;
import chamin.data.Club;
import chanaka.dao.StudentDAO;
import chanaka.data.Student;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import prabath.dao.TeacherDAO;
import prabath.data.Teacher;

/**
 *
 * @author chamin
 */
public class AddClub extends javax.swing.JDialog {

    DbConnector dbConnector;
    ClubDAO clubDAO;
    TeacherDAO teacherDAO;
    StudentDAO studentDAO;
    
    Teacher TeacherIn;
    Student President;
    Student VicePresident;
    Student Secretary;
    Student AssSecretary;
    Student Treasurer;
    
    int error[] = {0,0,0,0,0,0,0,0};

    public AddClub(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //set the form in mmdle of the window
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setLocation(dim.width/2-this.getWidth()/2, dim.height/2-this.getHeight()/2);
        this.setSize(dim.width, dim.height - 40);
        jScrollPane1.setSize(dim.width, dim.height - 40);
        jPanel1.setSize(dim.width, dim.height - 40);

        try {
            // create the central DAO
            dbConnector = new DbConnector();
            // make a DAO for Person class by sending in the DB Connection from dbConnector
            clubDAO = new ClubDAO(dbConnector.getMyConn());
            teacherDAO =new TeacherDAO(dbConnector.getMyConn());
            studentDAO = new StudentDAO(dbConnector.getMyConn());

        } catch (IOException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtClubId = new javax.swing.JTextField();
        txtClubName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPresidentId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTask = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtSecretaryId = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSuggestions = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAdvisor = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtMembersId = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtVicePresidentId = new javax.swing.JTextField();
        txtTreasurerId = new javax.swing.JTextField();
        txtAssSecretaryId = new javax.swing.JTextField();
        dtChooserDateOfEstablish = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtTeacherInchargeId = new javax.swing.JTextField();
        lblClubId = new javax.swing.JLabel();
        lblClubName = new javax.swing.JLabel();
        lblInchage = new javax.swing.JLabel();
        lblPresident = new javax.swing.JLabel();
        lblVicePresident = new javax.swing.JLabel();
        lblSecretary = new javax.swing.JLabel();
        lblAssSecretary = new javax.swing.JLabel();
        lblTreasurer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1327, 1000));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel1.setText("Add New Club");

        jLabel2.setText("Club Index Number* :");

        jLabel3.setText("Name* :");

        jLabel4.setText("Teacher Incharge's Index Number* :");

        txtClubId.setToolTipText("10 characters");
        txtClubId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClubIdFocusLost(evt);
            }
        });
        txtClubId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClubIdActionPerformed(evt);
            }
        });

        txtClubName.setToolTipText("100 characters");
        txtClubName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClubNameFocusLost(evt);
            }
        });

        jLabel5.setText("Advisors Names :");

        jLabel9.setText("President's Index Number :");

        txtPresidentId.setToolTipText("10 characters");
        txtPresidentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPresidentIdFocusLost(evt);
            }
        });

        jLabel10.setText("Vise President's Index Number :");

        jLabel11.setText("Secretary Index Number :");

        jLabel12.setText("Assistant Secretary Index :");

        jLabel13.setText("Treasurer Index :");

        jLabel25.setText("Task :");

        jLabel26.setText("Suggestions :");

        txtTask.setColumns(20);
        txtTask.setRows(5);
        txtTask.setToolTipText("1000 characters");
        jScrollPane2.setViewportView(txtTask);

        jLabel27.setText("Date of Establish :");

        jButton3.setText("Add");

        txtSecretaryId.setToolTipText("10 characters");
        txtSecretaryId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSecretaryIdFocusLost(evt);
            }
        });

        txtSuggestions.setColumns(20);
        txtSuggestions.setRows(5);
        txtSuggestions.setToolTipText("1000 characters");
        jScrollPane4.setViewportView(txtSuggestions);

        txtAdvisor.setColumns(20);
        txtAdvisor.setRows(5);
        txtAdvisor.setToolTipText("500 characters, use comma to separate");
        jScrollPane5.setViewportView(txtAdvisor);

        jLabel28.setText("Members Index List :");

        txtMembersId.setColumns(20);
        txtMembersId.setRows(5);
        txtMembersId.setToolTipText("Use comma to separate members");
        jScrollPane6.setViewportView(txtMembersId);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtVicePresidentId.setToolTipText("10 characters");
        txtVicePresidentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVicePresidentIdFocusLost(evt);
            }
        });

        txtTreasurerId.setToolTipText("10 characters");
        txtTreasurerId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTreasurerIdFocusLost(evt);
            }
        });

        txtAssSecretaryId.setToolTipText("10 characters");
        txtAssSecretaryId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAssSecretaryIdFocusLost(evt);
            }
        });

        dtChooserDateOfEstablish.setDateFormatString("MM-dd-yyyy");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel6.setText("* required");

        txtTeacherInchargeId.setToolTipText("100 characters");
        txtTeacherInchargeId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTeacherInchargeIdFocusLost(evt);
            }
        });
        txtTeacherInchargeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherInchargeIdActionPerformed(evt);
            }
        });

        lblClubId.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblClubId.setForeground(new java.awt.Color(51, 51, 51));

        lblClubName.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblClubName.setForeground(new java.awt.Color(51, 51, 51));

        lblInchage.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblInchage.setForeground(new java.awt.Color(51, 51, 51));

        lblPresident.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblPresident.setForeground(new java.awt.Color(51, 51, 51));

        lblVicePresident.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblVicePresident.setForeground(new java.awt.Color(51, 51, 51));

        lblSecretary.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblSecretary.setForeground(new java.awt.Color(51, 51, 51));

        lblAssSecretary.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblAssSecretary.setForeground(new java.awt.Color(51, 51, 51));

        lblTreasurer.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblTreasurer.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel25))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(624, 624, 624)
                                        .addComponent(jButton3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(202, 202, 202)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtVicePresidentId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPresidentId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAssSecretaryId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTreasurerId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtChooserDateOfEstablish, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtClubId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtClubName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtSecretaryId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                                            .addComponent(jScrollPane4)
                                            .addComponent(jScrollPane6)
                                            .addComponent(jScrollPane5)
                                            .addComponent(txtTeacherInchargeId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblClubId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblClubName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblInchage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPresident, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblVicePresident, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblSecretary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblAssSecretary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTreasurer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(553, 553, 553)
                        .addComponent(jLabel1)))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClubId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblClubId, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClubName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClubName, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTeacherInchargeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lblInchage, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPresidentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblPresident, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtVicePresidentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lblVicePresident, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(txtSecretaryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lblSecretary, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtAssSecretaryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lblAssSecretary, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTreasurerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lblTreasurer, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(481, 481, 481)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCancel)
                                    .addComponent(btnAdd)))))
                    .addComponent(dtChooserDateOfEstablish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int x=0;// check for errors
        for(int i :error){
            if(i==1){x=1;}
        }
        
        if (txtClubId.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Club Index field should filled");
        } else if (txtClubName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Club Name field should filled");
        } else if (txtTeacherInchargeId.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Teacher Incharge field should filled");
        } else if(x==1) {
            JOptionPane.showMessageDialog(null, "Fill the form correctly");
        }
        else{
            try {
                addClub();

                clearForm();
                // show success message
                JOptionPane.showMessageDialog(null, "Contact saved successfully");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex, "There is a error", JOptionPane.ERROR_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void txtClubIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClubIdFocusLost
        try {
            List<Club> list = null;
            list = clubDAO.searchClub(txtClubId.getText(), "Club Id");

            if (!list.isEmpty()) {
                lblClubId.setText("Duplicate index number");
                error[0] = 1;
            } else if(!txtClubId.getText().equals("")){
                
                try {
                    Integer.parseInt(txtClubId.getText());
                    lblClubId.setText("Valid Index");
                    error[0] = 0;
                } catch (NumberFormatException e) {
                    lblClubId.setText("Invalid index number.Enter Numeric input");
                    error[0] = 1;
                }
            }
            else{
                lblClubId.setText("Fill the field");
                error[0] = 1;
            }
        } catch (SQLException ex) {
            System.out.println("Sql Error happend");
        }
    }//GEN-LAST:event_txtClubIdFocusLost

    private void txtClubIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClubIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClubIdActionPerformed

    private void txtClubNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClubNameFocusLost
        try {
            List<Club> list = null;
            list = clubDAO.searchClub(txtClubName.getText(), "Club Name");

            if (!list.isEmpty()) {
                lblClubName.setText("Duplicate club name");
                error[1] = 1;
            } else if(!txtClubName.getText().equals("")){
                
                //lblClubName.setText("Valid name");
                //try {
                //    Integer.parseInt(txtClubId.getText());
                //    System.out.println("parsing to int");
                //    lblClubName.setText("Invalid name");
                //    error[1] = 1;
                //} catch (NumberFormatException e) {
                    lblClubName.setText("Valid name");
                    error[1] = 0;
                //}
            }
            else{
                lblClubName.setText("Fill the field");
                error[0] = 1;
            }
        } catch (SQLException ex) {
            System.out.println("Sql Error happend");
        }
    }//GEN-LAST:event_txtClubNameFocusLost

    private void txtTeacherInchargeIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTeacherInchargeIdFocusLost
        
        try {
            TeacherIn=teacherDAO.getTeacherById(txtTeacherInchargeId.getText());
            lblInchage.setText(TeacherIn.getNameWithin());
            error[2] = 0;
        } catch (SQLException ex) {
            lblInchage.setText("This index number is not in the database.First add the teacher.");
            error[2] = 1;
        }
        if(txtTeacherInchargeId.getText().equals("")){
            lblInchage.setText("");
            error[2] = 0;
        }
    }//GEN-LAST:event_txtTeacherInchargeIdFocusLost

    private void txtTeacherInchargeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherInchargeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherInchargeIdActionPerformed

    private void txtPresidentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPresidentIdFocusLost
        try {
            President =studentDAO.getStudentObject(txtPresidentId.getText());
            lblPresident.setText(President.getNameWithInitials());
            error[3] = 0;
        } catch (SQLException ex) {
            lblPresident.setText("This index number is not in the database.First add the student.");
            error[3] = 1;
        }
        if(txtPresidentId.getText().equals("")){
            lblPresident.setText("");
            error[3] = 0;
        }
    }//GEN-LAST:event_txtPresidentIdFocusLost

    private void txtVicePresidentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVicePresidentIdFocusLost
        try {
            VicePresident=studentDAO.getStudentObject(txtVicePresidentId.getText());
            lblVicePresident.setText(VicePresident.getNameWithInitials());
            error[4] = 0;
        } catch (SQLException ex) {
            lblVicePresident.setText("This index number is not in the database.First add the student.");
            error[4] = 1;
        }
        if(txtVicePresidentId.getText().equals("")){
            lblVicePresident.setText("");
            error[4] = 0;
        }
    }//GEN-LAST:event_txtVicePresidentIdFocusLost

    private void txtSecretaryIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSecretaryIdFocusLost
        try {
            Secretary=studentDAO.getStudentObject(txtSecretaryId.getText());
            lblSecretary.setText(Secretary.getNameWithInitials());
            error[5] = 0;
        } catch (SQLException ex) {
            lblSecretary.setText("This index number is not in the database.First add the student.");
            error[5] = 1;
            
        }
        if(txtSecretaryId.getText().equals("")){
            lblSecretary.setText("");
            error[5] = 0;
        }
    }//GEN-LAST:event_txtSecretaryIdFocusLost

    private void txtAssSecretaryIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAssSecretaryIdFocusLost
        try {
            AssSecretary=studentDAO.getStudentObject(txtAssSecretaryId.getText());
            lblAssSecretary.setText(AssSecretary.getNameWithInitials());
            error[6] = 0;
        } catch (SQLException ex) {
            lblAssSecretary.setText("This index number is not in the database.First add the student.");
            error[6] = 1;
        }
        if(txtAssSecretaryId.getText().equals("")){
            lblAssSecretary.setText("");
            error[6] = 0;
        }
    }//GEN-LAST:event_txtAssSecretaryIdFocusLost

    private void txtTreasurerIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTreasurerIdFocusLost
        try {
            Treasurer=studentDAO.getStudentObject(txtTreasurerId.getText());
            lblTreasurer.setText(Treasurer.getNameWithInitials());
            error[7] = 0;
        } catch (SQLException ex) {
            lblTreasurer.setText("This index number is not in the database.First add the teacher.");
            error[7] = 1;
        }
        if(txtTreasurerId.getText().equals("")){
            lblTreasurer.setText("");
            error[7] = 0;
        }
    }//GEN-LAST:event_txtTreasurerIdFocusLost

    private void addClub() throws SQLException {

        String ClubId = txtClubId.getText();
        String ClubName = txtClubName.getText();
        String TeacherInchargeId = txtTeacherInchargeId.getText();
        String Advisor = txtAdvisor.getText();
        String PresidentId = txtPresidentId.getText();
        String VisePresidentId = txtVicePresidentId.getText();
        String SecretaryId = txtSecretaryId.getText();
        String AssSecretaryId = txtAssSecretaryId.getText();
        String TreasurerId = txtTreasurerId.getText();
        String Task = txtTask.getText();
        String Suggestions = txtSuggestions.getText();
        Date DateOfEstablish = new java.sql.Date(dtChooserDateOfEstablish.getDate().getTime());

        String MemberIdList[] = {txtMembersId.getText()};  // check this

        Club club = new Club(ClubId, ClubName, TeacherInchargeId, Advisor, PresidentId, VisePresidentId, SecretaryId, AssSecretaryId, TreasurerId, Task, Suggestions, DateOfEstablish, MemberIdList);

        clubDAO.addClub(club);
        
        //update incharge
        TeacherIn.setAccessPriviledge(2);
        TeacherIn.setClubIncharge(TeacherIn.getClubIncharge()+"#"+ClubId);
        teacherDAO.updateAccess(TeacherIn);
        
        /*
        
        
        studentDAO.updateStudent(President, President.getAdmissionNumber());
        studentDAO.updateStudent(VicePresident, VicePresident.getAdmissionNumber());
        studentDAO.updateStudent(Secretary, Secretary.getAdmissionNumber());
        studentDAO.updateStudent(AssSecretary, AssSecretary.getAdmissionNumber());
        studentDAO.updateStudent(Treasurer, Rreasurer.getAdmissionNumber());
        */
    }/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    private void searchClub(String keyWord, String searchPera) {

    }

    public void clearForm() {
        txtClubId.setText("");
        txtClubName.setText("");
        txtTeacherInchargeId.setText("");
        txtAdvisor.setText("");
        txtPresidentId.setText("");
        txtVicePresidentId.setText("");
        txtSecretaryId.setText("");
        txtAssSecretaryId.setText("");
        txtTreasurerId.setText("");
        txtTask.setText("");
        txtSuggestions.setText("");
        dtChooserDateOfEstablish.setDate(new Date(0));

        txtMembersId.setText("");
        
        lblAssSecretary.setText("");
        lblClubId.setText("");
        lblClubName.setText("");
        lblInchage.setText("");
        lblPresident.setText("");
        lblSecretary.setText("");
        lblTreasurer.setText("");
        lblVicePresident.setText("");
        
        
        
        
        
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddClub dialog = new AddClub(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private com.toedter.calendar.JDateChooser dtChooserDateOfEstablish;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblAssSecretary;
    private javax.swing.JLabel lblClubId;
    private javax.swing.JLabel lblClubName;
    private javax.swing.JLabel lblInchage;
    private javax.swing.JLabel lblPresident;
    private javax.swing.JLabel lblSecretary;
    private javax.swing.JLabel lblTreasurer;
    private javax.swing.JLabel lblVicePresident;
    private javax.swing.JTextArea txtAdvisor;
    private javax.swing.JTextField txtAssSecretaryId;
    private javax.swing.JTextField txtClubId;
    private javax.swing.JTextField txtClubName;
    private javax.swing.JTextArea txtMembersId;
    private javax.swing.JTextField txtPresidentId;
    private javax.swing.JTextField txtSecretaryId;
    private javax.swing.JTextArea txtSuggestions;
    private javax.swing.JTextArea txtTask;
    private javax.swing.JTextField txtTeacherInchargeId;
    private javax.swing.JTextField txtTreasurerId;
    private javax.swing.JTextField txtVicePresidentId;
    // End of variables declaration//GEN-END:variables
}
